Script "stack_revRefactor_field_id_1011"

/*
# Name: field "lblAbout" of card "card id 1002" of stack "revRefactor"
# ID: field id 1011 of card id 1002 of stack "revRefactor"
*/


on revHookBuildScriptEditorMenu pMenuName, pMenu, @pModifiedMenu
   breakpoint
end revHookBuildScriptEditorMenu

on revHookBuildScriptEditorContextMenu pObjectID, pSelectedText, pText, @pModifiedText
   breakpoint
end revHookBuildScriptEditorContextMenu
